# Generated by Django 4.2.26 on 2026-03-09 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Штрих-код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('calories', models.FloatField(default=0, verbose_name='Ккал (на 100г)')),
                ('proteins', models.FloatField(default=0, verbose_name='Белки')),
                ('fats', models.FloatField(default=0, verbose_name='Жиры')),
                ('carbs', models.FloatField(default=0, verbose_name='Углеводы')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на картинку')),
            ],
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=100, verbose_name='Вес съеденного (грамм)')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус')], max_length=20, verbose_name='Прием пищи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
