# Generated by Django 4.2.26 on 2026-05-07 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition', '0003_dailywater'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='Кто добавил это блюдо (null = администратор)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dishes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='is_global_dish',
            field=models.BooleanField(default=False, verbose_name='В глобальной библиотеке'),
        ),
    ]
