# Generated by Django 4.2.26 on 2026-05-26 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_product_creator_product_is_global_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата употребления'),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления (в БД)'),
        ),
    ]
