# Generated by Django 4.2.26 on 2026-05-28 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAdviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_text', models.TextField(verbose_name='Текст совета от ИИ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_advices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Совет ИИ',
                'verbose_name_plural': 'Советы ИИ',
            },
        ),
    ]
