# Generated by Django 4.2.26 on 2026-05-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiadvicelog',
            name='status',
            field=models.CharField(choices=[('processing', 'Генерируется...'), ('ready', 'Готово'), ('error', 'Ошибка')], default='processing', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='aiadvicelog',
            name='advice_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст совета от ИИ'),
        ),
    ]
