# Generated by Django 4.2.26 on 2026-02-14 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата сдачи')),
                ('laboratory', models.CharField(blank=True, max_length=100, verbose_name='Лаборатория')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Biomarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('A', 'Любой')], default='A', max_length=1, verbose_name='Пол')),
                ('min_age', models.PositiveIntegerField(default=0, verbose_name='Возраст от')),
                ('max_age', models.PositiveIntegerField(default=100, verbose_name='Возраст до')),
                ('min_value', models.FloatField(verbose_name='Нижняя граница нормы')),
                ('max_value', models.FloatField(verbose_name='Верхняя граница нормы')),
                ('biomarker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='analyses.biomarker')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('status', models.CharField(blank=True, choices=[('low', 'Ниже нормы'), ('norm', 'Норма'), ('high', 'Выше нормы'), ('unknown', 'Нет нормы')], default='unknown', max_length=10, verbose_name='Статус')),
                ('biomarker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyses.biomarker')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analyses.analysisrecord')),
            ],
        ),
    ]
